
DEFAULT_LINKS_CSV_FILE_NAME = "links.csv"
TEMP_FILE_NAME = "temp.csv"
DEFAULT_OUTPUT_FILENAME = 'data.csv'

#classes used
TOKEN_INFORMATION_CLASSES = ["financial_data"]
TOKEN_INFORMATION_ROW_CLASSES = ["data_row"]
LISTING_LINK_CLASSES = ["name"]
NAME_CLASSES = ["name"]
ICO_INFORMATION_CLASSES = ['ico_information']
CATEGORIES_CLASSES = ['categories']
VALUE_OF_TOKENS_SOLD_CLASSES = ['raised']
SOCIAL_LINKS_CLASSES = ['socials']
TAB_CONTENT_CLASSES = ['tab_content']
MEMBER_ROW_CLASSES = ["row"]
MEMBER_CLASSES = ["col_3"]
MILESTONES_ROW_CLASSES = ["row"]
MILESTONE_BUBBLE_CLASSES = ["bubble"]
MILESTONE_YEAR_CLASSES = ["condition"]
LEFT_FINANCIAL_BOX_CLASSES = ["box_left"]
RIGHT_FINANCIAL_BOX_CLASSES = ["box_right"]
WHITE_PAPER_LINK_TEXT = "White paper"
FIXED_DATA_CLASSES = ["fixed_data"]
FINANCIAL_ROW_CLASSES = ["row"]
FINANCIAL_ROW_LABEL_CLASSES = ["label"]
FINANCIAL_ROW_VALUE_CLASSES = ["value"]
INVESTMENT_ROW_CLASSES = ["row"]
INVESTMENT_ROW_LABEL_CLASSES = ["label"]
INVESTMENT_ROW_VALUE_CLASSES = ["value"]
BONUS_TEXT_CLASSES = ["bonus_text"]

#ids used
DESCRIPTION_ID = "about"
TEAM_ID = "team"
MILESTONES_ID = "milestones"
FINANCES_ID = "financial"